# CSCI1470 Lab 1: Python Refresher + NumPy Intro
***important***: Before starting the lab please copy this notebook into your own google drive by clicking on "File" and "Save a copy in drive"

<img src="https://drive.google.com/uc?export=view&id=1dpFAr9rA-qPbGKHXfmKRZvN0BuYzFSUP" alt="meme.jpg" width="400">

This course will be primarily taught in TensorFlow on Python3. TensorFlow is an open source deep learning library created by Google. Currently it is the most popular and widely used library.

This lab is a refresher on Python3 and basic linear algebra; you will be expected to be familiar with both in this class. **Treat this lab as your ONLY opportunity to ask questions about general coding with Python: this is a class on deep learning, not software engineering. For every upcoming assignment and labs, you will be expected to have a working knowledge of Python and linear algebra.**

Visit [this link](https://www.python.org/downloads/) for instructions on how to install Python on your system. If you are installing locally, please use **Python3.9, 64-bit version** for consistency purposes. (IMPORTANT: TensorFlow requires a 64-bit installation of Python!)


Visit [this link](https://docs.google.com/document/d/16kkj9O2JnMFhIbHF6iZpCseloBduDSVT-B-U9R8WKcA/edit?usp=sharing) for instructions on how to setup virtualenvs (virtual environments) for easy, isolated Python workspaces.

## Hello World ##
Printing in Python can be done with the `print` function. 

This is one of many functions that are pre-loaded in when a Python interpreter instance is created. Try running it!

In [ ]:
print("Hello World!")

## Libraries ##

Python has a number of built-in modules and libraries that offer convenient access to useful functions. These libraries can be imported by using the built-in `import` function followed by the library name.

Here is one example with the `random` library that can be used for generating a series of random integers within some specified range. 

Note that `for i in range(5)` is analogous to `for (int i = 0; i < 5; i++)` in Java. `range(5)` is an iterable object, and is functionally similar to `for i in [0, 1, 2, 3, 4]`. The `:` (colon) indicates the creation of a scope, so the indented section after the `for` loop will be iterated for every value in the output of `range(5)`.

In [ ]:
import random
for i in range(5):
    print(random.randint(10,99))

## Indentation ##
Notice that Python uses indentation and colons in order to specify scope, as opposed to brackets. This means that you need to be careful to make sure that all of your code is indented correctly.

In [ ]:
x = 0
 
while x < 10:
    if x % 2 == 0:
        print(x)
    x += 1
 
print('done.')

## Dynamic Typing ##
In Python, variables are associated with single objects and no data types. Furthermore, primitive data types in Python are immutable.

In [ ]:
var = 5
print(var)
print(type(var))

var = 'spam'
print(var)
print(type(var))

## Strings ##
Python supports strings along with the expected indexing schema and methods.

In [ ]:
mystring = 'ham and eggs'
print(mystring[0:4]) # note that the first index is inclusive and the second index is exclusive
print(mystring.find('and'))
print(mystring.split(' '))

## Lists ##
Lists/arrays are mutable objects in Python.

In [ ]:
mylist = [1, 2]
mylist.append("three")

print(mylist)

## Tuples ##
Tuples are like immutable lists. However their constituent elements can be altered.

In [ ]:
tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')

try:
    tup1[0] = 100;
except TypeError:
    print('See why this returns an error?')


tup3 = tup1 + tup2 # this concatenates the two tuples
print(tup3)
print(len(tup3))
for x in tup3: print(x)

## Dictionaries ##
Python also supports dictionaries (hash maps) for mapping between specified keys and values.

In [ ]:
numbers = {'one': 1, 'two': 2, 'three': 3, 'four': 4 }
print(numbers['one'])
del numbers['one']  # Remove an entry from the dictionary

try:
    print(numbers['one'])
except KeyError:
    print("This shouldn't work, since we deleted numbers['one'] above")

print(numbers)
print(numbers.keys())
print(numbers.values())

## Name binding ##
Notice that Python assignment binds a name to a particular object. Some objects, such as integers and strings, are considered **immutable**. For these, you can safely bind a new name to an object and change it however you'd like, and the value referenced from the old name will not change (i.e. pass-by-value-like). However, containers and certain object types might be **mutable**, in which case modifying a (shallow) copy of the original will modify all instances of the object (pass-by-reference-like). For more details, consider checking out [this page on Call by Object Reference](https://www.geeksforgeeks.org/is-python-call-by-reference-or-call-by-value/). 

***If your goal is to make an independent clone of a general object, you should use the `deepcopy` function from Python's `copy` library. Alternatively, you can use the `list` function to copy a list. When using numpy, feel free to look into copying options (i.e. `.copy()`)

In [ ]:
print('Pass-By-Reference-like')
a = [1, 2]
b = a
print(f'A = {a} \t B = {b}')
b.append(3)
print(f'A = {a} \t B = {b}')

print('\nPass-By-Value-like')
a = 1
b = a
print(f'A = {a} \t\t B = {b}')
b = b + 1
print(f'A = {a} \t\t B = {b}')


## Control Flow ##
Here are examples of if-else statements, for loops, and while loops in Python. Notice how identation controls scope in each statement.

In [ ]:
age = 22
 
if age < 13:
    print('kid')
elif age < 18:
    print('teen')
else:
    print('adult')

In [ ]:
for i in range(5):
    pass
 
for i in [0, 1, 2, 3, 4]:
    if i > 5:
        break
else:
    print('Python supports the else keyword for for-loops, which execute if the loop completes without breaking')

In [ ]:
x = 1024
 
while x > 1:
    x = x / 2
    if (x % 10) != 2:
        continue
    print(x)

## Functions ##
Specify functions using the `def` keyword and create a new name binding in the local space. They can also be assigned directly to variables using the `lambda` keyword (use sparingly).

**NOTE!!** You are allowed to override core methods, for example: 
```
def sum(a, b):
    return a + b
```

This is almost-always a terrible idea! Try to make sure that you don't override anything like that unless you really mean to. 

In [ ]:
def example_func(s="hello!"):
    print(s)
 
example_func("goodbye!")
example_func() 
# This is equivalent to example_func("hello!") since we 
# give the parameter 's' a default value of "hello!"

Functions can also be passed as variables. This may come in handy when implementing generalizable code. 

In [ ]:
import math

def apply_and_print(a, b, op=lambda a, b: (a, b)):
    '''
    Apply a method to a pair of numbers and then print it. 
    By default, use identity function (aka just return the values)
    '''
    return print('Output:', op(a, b))

apply_and_print(4, 5)
apply_and_print(4, 5, math.pow)
apply_and_print(4, 5, print)
apply_and_print(4, 5, lambda a, b: a**2 + b**2)  # shorthand lambda syntax

## Fibonacci (Checkoff)

In [94]:
from typing import List
# TODO implement fibonacci numbers
# parameters: num -> int, numbers of fibonacci's to generate
# returns:    sequence -> list, generated fibonacci sequence

def fibonacci(num: int) -> List[int]:
    list = []
    v1 = 0
    v2 = 1
    list.append(v1)
    list.append(v2)
    for x in range(2, num):
        v3 = v1 + v2
        list.append(v3)
        v1 = v2
        v2 = v3 
    return list
print(fibonacci(16))
assert(fibonacci(10)[9] == 34)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610]


## Classes ##
Specify classes using the `class` keyword. Notice the `__` around the first method of this class; this denotes what are more commonly referred to as ["magic methods"](http://minhhh.github.io/posts/a-guide-to-pythons-magic-methods) in Python. The magic method defined for this class is the constructor that you will need to define for all your classes.

In [ ]:
import math
 
class BasicVector:
    def __init__(self, x, y):
        '''
        The Vector2 object can have 'properties' assigned to it. 
        'self', the first argument, is a particular object instance.
        We can assign values to it as follows: 
        '''
        self.x = x
        self.y = y
 
    def len(self):
        '''Useful method that can be called by all instances of the object'''
        return math.sqrt(self.x ** 2 + self.y ** 2)

    def __str__(self):
        '''
        One of many possible overrideable methods. 
        This one says what the string version is, which is what print uses...
        '''
        return f'V{(self.x, self.y)}'

 
v = BasicVector(3, 4)
print(f'v = {v} or {(v.x, v.y)}')
print(f'v.len() = {v.len()}')
try:
    print(f'v + v = {v + v}')
except Exception as e: 
    print('Vector addition not implemented, so: \n\t Exception:', e)

v = V(3, 4) or (3, 4)
v.len() = 5.0
Vector addition not implemented, so: 
	 Exception: unsupported operand type(s) for +: 'BasicVector' and 'BasicVector'


A class can also be sub-classed, where we can add onto the default implementation with additional customizations

In [ ]:
class Vector(BasicVector):
    def __init__(self, x, y, name='V'):
        super().__init__(x, y)  ## Initiate the init method of super-class
        self.name = name

    def __str__(self): return f'{self.name}{(self.x, self.y)}'
    
    def __add__(self, other):   
        return self.__class__(self.x + other.x, self.y + other.y)
    def __sub__(self, other):   
        return self.__class__(self.x - other.x, self.y - other.y) 

v1 = Vector(3, 4)
v2 = Vector(5, 6)

print(f'v1 = {v1}')
print(f'v2 = {v2}')

print(f'v1.len() = {v1.len()}')

print(f'v1 + v2 = {v1 + v2}')
print(f'v1 - v2 = {v1 - v2}')

v1 = V(3, 4)
v2 = V(5, 6)
v1.len() = 5.0
v1 + v2 = V(8, 10)
v1 - v2 = V(-2, -2)


## Logger Class (Checkoff)

For a check-off, you are going to implement a logging wrapper for your Vector2. In other words, you are going to log when operations happen on your objects and then print them out. 

This will require storing an inputted vector as a class instance and then calling the operations on its behalf. This is an example of hiding complexity from the user to facilitate background functionality (which is going to be very common going forward). Some of the methods have already been pre-filled for you. Please implement the additional methods as necessary to get the desired result. Note that the result of `Logger` operations should also be `Logger` instances.

In [92]:
 class Logger:
    def __init__(self, v):
        assert isinstance(v, Vector)
        self.v = v
        self._logs = []                            ## Internal variable to hold logs

    def _log_get(self, msg, val):
        '''Utility Method: Adds entry to the log and returns the value'''
        self._logs += [f'{msg} [{val}]']           ## Append to a list
        return val

    def __call__(self):
        '''Call override'''
        print(f'{self.v} Logs:')
        [print(f' - {log}') for log in self._logs] ## List comprehension loop

    def __str__(self):   
        #return self ## TODO
        self._log_get("Query String", self.v)
        return f'{self.v}'
    
    def __add__(self, b): 
        #return self ## TODO
        self._log_get("Query " + f'{self.v}' + " + " + f'{b.v}', self.v + b.v)
        return self.__class__(self.v + b.v)
    
    def __sub__(self, b): 
        #return self ## TODO
        self._log_get("Query " + f'{self.v}' + " - " + f'{b.v}',  self.v - b.v)
        return self.__class__(self.v - b.v)


v1 = Logger(Vector(3, 4, name='myV1'))
v2 = Logger(Vector(5, 6, name='myV2'))

print(f'v1 = {v1}')
print(f'v2 = {v2}')

v3 = v1 + v2
v4 = v1 - v2
print(f'v1 + v2 = {v3}')
print(f'v1 - v2 = {v4}')

print(); v1()   ## quick hack for issuing commands back-to-back. Use sparingly
print(); v2()
print(); v3()
print(); v4()

v1 = myV1(3, 4)
v2 = myV2(5, 6)
v1 + v2 = V(8, 10)
v1 - v2 = V(-2, -2)

myV1(3, 4) Logs:
 - Query String [myV1(3, 4)]
 - Query myV1(3, 4) + myV2(5, 6) [V(8, 10)]
 - Query myV1(3, 4) - myV2(5, 6) [V(-2, -2)]

myV2(5, 6) Logs:
 - Query String [myV2(5, 6)]

V(8, 10) Logs:
 - Query String [V(8, 10)]

V(-2, -2) Logs:
 - Query String [V(-2, -2)]


EXPECTED:
```
v1 = myV1(3, 4)
v2 = myV2(5, 6)
v1 + v2 = V(8, 10)
v1 - v2 = V(-2, -2)

myV1(3, 4) Logs:
 - Query String [myV1(3, 4)]
 - Query myV1(3, 4) + myV2(5, 6) [V(8, 10)]
 - Query myV1(3, 4) - myV2(5, 6) [V(-2, -2)]

myV2(5, 6) Logs:
 - Query String [myV2(5, 6)]

V(8, 10) Logs:
 - Query String [V(8, 10)]

V(-2, -2) Logs:
 - Query String [V(-2, -2)]
```

## Linear Algebra Refresher
Before moving on to NumPy, we need to talk about our favourite type of math: Linear Algebra. Most of the operations in Deep Learning are done by matrices. It's both practical and easy to optimise using very powerful parallel hardwares like GPUs. For the purpose of this lab and most of this course, we only really need to know about matrix multiplications. Let's take a look at how that works.

Given the following two matrices: 
``` Python
A = [[1,2,3],[4,5,6]]      # Shape=(2,3)
B = [[7,8],[9,10],[11,12]] # Shape=(3,2)
```
And we want to find A * B, to do this we dot the rows of A and the columns of B to find each element in AB:
<img alt="matrix 1" src='https://drive.google.com/uc?export=view&id=
1lVFYIBIJE4H-lDPbwmwzorpxLNWuFX-H'>
<img alt="matrix 2" src='https://drive.google.com/uc?export=view&id=
1ZvLso_4JI5OJJKh93MNBhgq3WMHSlp-H'>
<img alt="matrix 3" src='https://drive.google.com/uc?export=view&id=
1iN7nASb6lCBh_uP1iUr6ymuyYb-crhVm'>

Take note of the resultant shape of the multiplication. When we have a matrix of shape (N, M) multiplied by a matrix of shape (M, V), we end up with a matrix of shape (N, V). If the last dimension of the first matrix and the first dimension of the matrix do not match, the multiplication won't work. 

Matrix multiplication can also work with a vector and a matrix since a vector is a (length, 1) matrix.

## NumPy (Numeric Python) ##
For much of this course, you will often find yourself in need of creating, modifying, and combining n-dimensional arrays. Numpy is the standard Python library for quickly, cleanly, and efficiently performing all of these functions.

Here are just a few examples with basic Numpy arrays. 

For a more in-depth view of the other useful features of Numpy, visit [this tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy).

### Basics

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


###Indexing into arrays

In [ ]:
# Similar to lists, numpy arrays can be sliced
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1, 2:]) # Prints columns 3 and up in the 2nd row of b 

# Boolean indexing
print(a > 5) # Prints true for each element greater than 5

# Reversing a numpy array
b = np.array([1,2,10])
print(b[::-1])

[ 8  9 10]
[[False False False False False]
 [ True  True  True  True  True]]
[10  2  1]


### Some custom functions to create arrays.

In [ ]:
import numpy as np

a = np.zeros((2,2))             # Create an array of all zeros
print(a)                        # Prints "[[ 0.  0.]
                                #          [ 0.  0.]]"

b = np.ones((1,2))              # Create an array of all ones
print(b)                        # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)           # Create a constant array
print(c)                        # Prints "[[ 7.  7.]
                                #          [ 7.  7.]]"

d = np.eye(2)                   # Create a 2x2 identity matrix
print(d)                        # Prints "[[ 1.  0.]
                                #          [ 0.  1.]]"

e = np.random.random((2,2))     # Create an array filled with random values
print(e)                        # Might print "[[ 0.91940167  0.08143941]
                                #               [ 0.68744134  0.87236687]]"

### Array operations.
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce an array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce an array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce an array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce an array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces an array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

# Type conversion; copies the array, casting the types of the elements
# [[1,2],[3,4]], np.uint8
print(x.astype(np.uint8), type(x.astype(np.uint8)[0][0]))

# Transpose; reverses the order of axes (parallels matrix transpose in 2D)
# [[ 0  2]
#  [ 1  3]]
x1 = np.array([[0, 1], [2, 3]]).T # np.transpose(x1) also works
print(x1)

# Reshape; changes the dimensions of a matrix
# [[ 1.  2.  3.  4.]]
x2 = np.reshape(x, [1, 4])
print(x2)

# Max; returns the value of the largest element
# 4.0
print(np.max(x2))

# Argmax; returns the index of the largest element
# 3
print(np.argmax(x2))

# Mean; returns mean of all elements in array
# 2.5
print(np.mean(x))

# Sum; returns sum of all elements in array
# 10.0
print(np.sum(x))

# Note: if you set a value to the argument axis (if the function has that 
# argument), the operation will be applied along that axis. Ex. if we apply
# np.max to a 2D array and specify axis=0, it will get the max of every row
# [1, 3]
x3 = np.max(np.array([[0, 1], [2, 3]]), axis=0)
print(x3)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1 2]
 [3 4]] <class 'numpy.uint8'>
[[0 2]
 [1 3]]
[[1. 2. 3. 4.]]
4.0
3
2.5
10.0
[2 3]


In [ ]:
import numpy as np
# Arange(a,b); creates a 1D array from a to b inclusive
print(np.arange(2,10))

# Concatenate; Join a sequence of arrays along an existing axis
# Hstack; Stack arrays in sequence horizontally (column wise)
print(np.hstack((np.ones((5,1)), np.zeros((5,1)))))

# Vstack; Stack arrays in sequence vertically (row wise)
print(np.vstack((np.ones((1,5)), np.zeros((1,5)))))

# Expand_dims; Expand the shape of an array
  # Note: Squeeze does the opposite by removing axes of length 1
print(np.array([1, 2]).shape, np.expand_dims(np.array([1, 2]), axis=1).shape)

# Split; Splits an array (along axis 0) into a specified number of smaller arrays
print(np.split(np.arange(10), 5))

### Matrix multiplication

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# Matmul and dot are the same for 2D operations, but differ when we increase dimensionalities.
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.matmul(x, y))

### Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

### Multiple Dimensional Matrix Multiplication

In [ ]:
import numpy as np

# Let's say we have the following matrix A
A = np.random.random((50, 100, 20))
# We can imagine A as 50 instances of (100,20) matrices.
# We have the following matrix B
B = np.random.random((20,40))
# We want to multiply each (100,20) instance of A by B, we can do this because the dimensions match up: 20 = 20
print(np.dot(A,B).shape) 
# should be (50, 100, 40), each of the 50 (100,20) is multiplied by (20,40) matrix to yield (100, 40)

#### P.S. on Numpy
Stackoverflow it.

### Numpy Matrix Operations (Checkoff)
Implement some of the numpy matrix operations described earlier.

In [93]:
import numpy as np
A = np.array([[0,1,2],[3,4,5]]) # shape (2,3)
B = np.array([[1,1,1]]) # shape (1,3)
C = np.array([[-1,-1,-1],[1,1,1]]) # shape (2,3)

# TODO
# Create matrix "D" as A - B using broadcasting
# Create matrix "E" with shape (3,2) by reshaping C
# Create matrix "F" with shape (2,2) by matrix multiplying "D" by "E"
D = np.subtract(A, B)
E = np.reshape(C, [3, 2])
F = np.dot(D, E)
assert(np.all(D == [[-1,0,1],[2,3,4]]))
assert(np.all(E == [[-1,-1],[-1,1],[1,1]]))
assert(np.all(F == [[2,2],[-1,5]]))

## Acknowledgements & Sources ##
This tutorial was adapted from an analogous tutorial and slides developed by Zhenyu Zhou, Richard Guo, Cam Allen-Lloyd, and Nakul Gopalan, and is based on the
Python Numpy Tutorial written by Justin Johnson for Stanford's CS231n: Convolutional Neural Networks for Visual Recognition.

Wikibooks

A Guide to Python's Magic Methods by Ha Minh

This lab is written by Bryce Blinn and James Wang, with the original version by Philip Xu.